let htmlTopic = document.getElementById("topic");


function getTopic() {
    console.log(htmlTopic);
    
    htmlTopic.innerHTML = getRandomTopic();


}

function getRandomTopic() {
    let size = speakingQuestions.length;
    return speakingQuestions[ getRandomIntInclusive(0, size - 1) ]
}

function getRandomIntInclusive(min, max) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min + 1)) + min;
}





const speakingQuestions = [
  // --- Personal & Lifestyle (1-30) ---
  "How do you usually spend your weekends?",
  "What is your favorite time of day and why?",
  "How do you handle stress or pressure?",
  "What is the most interesting hobby you have ever tried?",
  "How would you describe your perfect day?",
  "What is a habit you are trying to build right now?",
  "Who has had the biggest influence on your life?",
  "What is your earliest childhood memory?",
  "How do you like to celebrate your birthday?",
  "What is your biggest fear?",
  "How do you define happiness?",
  "What is one thing you cannot leave the house without?",
  "How do you stay organized in your daily life?",
  "What is the best advice you have ever received?",
  "How do you feel about getting older?",
  "What is your favorite season and why?",
  "How do you relax after a long day?",
  "What is a hidden talent that you have?",
  "How do you deal with failure?",
  "What is your proudest achievement so far?",
  "How would your friends describe you in three words?",
  "What is a goal you want to achieve this year?",
  "How do you motivate yourself when you feel lazy?",
  "What is your favorite book or movie, and why?",
  "How do you feel about public speaking?",
  "What is something you wish you were better at?",
  "How do you spend your mornings?",
  "What is the most adventurous thing you have ever done?",
  "How do you handle criticism?",
  "What is something simple that makes you smile?",

  // --- Travel & Adventure (31-60) ---
  "What is your dream travel destination?",
  "How do you prefer to travel: alone or with a group?",
  "What is the most beautiful place you have ever visited?",
  "How do you handle culture shock when traveling?",
  "What is the worst travel experience you have ever had?",
  "How do you prepare for a long trip?",
  "What is your favorite mode of transportation?",
  "How do you feel about staycations versus traveling abroad?",
  "What is the best meal you have ever had while traveling?",
  "How important is knowing the local language when visiting a country?",
  "What are three things you always pack in your suitcase?",
  "How do you feel about camping versus staying in hotels?",
  "What is a city you would love to live in for a year?",
  "How do you decide where to go on vacation?",
  "What is the most overrated tourist attraction you have seen?",
  "How do you pass the time during long flights?",
  "What is a souvenir you cherish from a trip?",
  "How do you navigate a city without a map or phone?",
  "What is the scariest moment you have had while traveling?",
  "How do you feel about guided tours?",
  "What is a country you have no interest in visiting?",
  "How do you save money for travel?",
  "What is the most interesting person you met while traveling?",
  "How does traveling change your perspective on life?",
  "What is your opinion on space tourism?",
  "How do you deal with jet lag?",
  "What is the longest road trip you have ever taken?",
  "How do you feel about cruises?",
  "What is a local custom from another country that surprised you?",
  "How would you describe your country to a tourist?",

  // --- Work & Career (61-90) ---
  "What was your first job and what did you learn from it?",
  "How do you handle a difficult boss or coworker?",
  "What is your dream job?",
  "How do you feel about working remotely vs. in an office?",
  "What is the most important soft skill in the workplace?",
  "How do you maintain a work-life balance?",
  "What is a career path you would never choose?",
  "How do you prepare for a job interview?",
  "What is the biggest challenge in your current field?",
  "How do you deal with burnout?",
  "What is your opinion on the four-day work week?",
  "How important is salary compared to job satisfaction?",
  "What is the best way to ask for a raise?",
  "How do you handle tight deadlines?",
  "What is your opinion on office dress codes?",
  "How do you network effectively?",
  "What is a mistake you made at work and how did you fix it?",
  "How do you see your industry changing in the next 10 years?",
  "What is the value of teamwork versus individual work?",
  "How do you handle constructive feedback?",
  "What is your opinion on internships?",
  "How do you stay productive when working from home?",
  "What is the most unusual job you have heard of?",
  "How do you feel about artificial intelligence replacing jobs?",
  "What would you do if you didn't have to work for money?",
  "How do you define success in your career?",
  "What is the hardest decision you had to make at work?",
  "How do you handle workplace gossip?",
  "What is your leadership style?",
  "How do you unwind after a stressful week at work?",

  // --- Education & Learning (91-120) ---
  "What was your favorite subject in school?",
  "How do you learn best: reading, listening, or doing?",
  "What is a skill you are currently trying to learn?",
  "How do you feel about online education versus traditional classrooms?",
  "What is the most valuable lesson you learned outside of school?",
  "How important is a university degree today?",
  "What is a language you would love to speak fluently?",
  "How do you improve your memory?",
  "What is a book that changed your way of thinking?",
  "How do you stay focused when studying?",
  "What is your opinion on homework?",
  "How did your favorite teacher influence you?",
  "What is a subject that should be taught in schools but isn't?",
  "How do you handle exam stress?",
  "What is the hardest thing you have ever had to learn?",
  "How do you feel about group projects?",
  "What is the importance of learning history?",
  "How do you keep yourself updated with current events?",
  "What is a documentary that taught you something new?",
  "How do you verify if information is true or false?",
  "What is the benefit of learning a musical instrument?",
  "How has the internet changed the way we learn?",
  "What is your opinion on standardized testing?",
  "How do you teach yourself a new hobby?",
  "What is the most boring subject you ever studied?",
  "How important is financial literacy?",
  "What is a skill you wish you learned as a child?",
  "How do you encourage someone to keep learning?",
  "What is the difference between being smart and being wise?",
  "How do you plan to educate yourself in the future?",

  // --- Technology & Future (121-150) ---
  "How much time do you spend on your phone daily?",
  "What is the most useful app you have installed?",
  "How do you feel about social media's impact on mental health?",
  "What is a piece of technology you cannot live without?",
  "How do you think cars will look in 50 years?",
  "What is your opinion on self-driving cars?",
  "How do you protect your privacy online?",
  "What is the future of virtual reality?",
  "How do you feel about genetic engineering?",
  "What is a gadget you wish existed?",
  "How has technology changed dating?",
  "What is your opinion on cryptocurrency?",
  "How do you handle internet trolls?",
  "What is the positive side of social media?",
  "How do you think AI will change education?",
  "What is a video game you enjoy playing?",
  "How do you feel about facial recognition technology?",
  "What is the most annoying thing about modern technology?",
  "How do you think we will communicate in the future?",
  "What is the impact of streaming services on cinema?",
  "How do you manage your digital footprint?",
  "What is your favorite tech brand and why?",
  "How do you feel about robots in the home?",
  "What is the danger of relying too much on GPS?",
  "How has the internet changed shopping?",
  "What is the next big technological breakthrough?",
  "How do you feel about 3D printing?",
  "What is your opinion on the metaverse?",
  "How do you disconnect from technology?",
  "What is the role of ethics in technology?",

  // --- Hypothetical Questions (151-180) ---
  "If you won the lottery today, what is the first thing you would buy?",
  "If you could have any superpower, what would it be?",
  "If you could travel back in time, which era would you visit?",
  "If you could have dinner with any historical figure, who would it be?",
  "If you were stuck on a deserted island, what three things would you bring?",
  "If you could switch lives with anyone for a day, who would it be?",
  "If you could only eat one food for the rest of your life, what would it be?",
  "If animals could talk, which one would be the rudest?",
  "If you were the leader of your country, what is the first law you would pass?",
  "If you could master any skill instantly, what would you choose?",
  "If you had to live in a movie, which one would you pick?",
  "If you could change one thing about your past, what would it be?",
  "If you found a wallet with money and an ID, what would you do?",
  "If you could be invisible for a day, what would you do?",
  "If you could speak to your younger self, what advice would you give?",
  "If you had to give up the internet or music, which would you choose?",
  "If you could cure one disease, which one would it be?",
  "If you were famous, what would you want to be famous for?",
  "If you could restart your life in a different country, where would you go?",
  "If you could eliminate one world problem, what would it be?",
  "If you had unlimited money but only 24 hours to spend it, what would you do?",
  "If you could know the date of your death, would you want to know?",
  "If you were a ghost, who would you haunt?",
  "If you could invent a new holiday, what would it celebrate?",
  "If you had to teach a class on one subject, what would it be?",
  "If you could change your name, what would you change it to?",
  "If you could understand what your pet is thinking, would you want to?",
  "If you had to lose one of your five senses, which one would it be?",
  "If you could witness any event in history, what would it be?",
  "If you were an alien, what would you think of humans?",

  // --- Food & Health (181-210) ---
  "What is your favorite comfort food?",
  "How do you feel about vegetarian or vegan diets?",
  "What is a food you absolutely hate?",
  "How often do you cook at home?",
  "What is the weirdest food you have ever tried?",
  "How do you stay fit and healthy?",
  "What is your opinion on fast food?",
  "How much water do you drink a day?",
  "What is your favorite dessert?",
  "How do you feel about organic food?",
  "What is a traditional dish from your culture?",
  "How do you take your coffee or tea?",
  "What is your favorite restaurant?",
  "How do you handle late-night cravings?",
  "What is the most expensive meal you've ever eaten?",
  "How do you feel about counting calories?",
  "What is a healthy habit you want to start?",
  "How does lack of sleep affect you?",
  "What is your favorite fruit?",
  "How do you feel about spicy food?",
  "What is the best breakfast you've ever had?",
  "How do you motivate yourself to exercise?",
  "What is your opinion on supplements and vitamins?",
  "How has your diet changed over the years?",
  "What is a food combination that sounds weird but tastes good?",
  "How do you feel about sugary drinks?",
  "What is your favorite cuisine (Italian, Mexican, Asian, etc.)?",
  "How do you deal with a headache naturally?",
  "What is the importance of mental health awareness?",
  "How do you relax your muscles after a workout?",

  // --- Abstract & Deep Topics (211-230) ---
  "What does freedom mean to you?",
  "Do you believe that money can buy happiness?",
  "Is it better to be loved or respected?",
  "Do you believe in fate or free will?",
  "What makes a person truly beautiful?",
  "Is honesty always the best policy?",
  "What is the meaning of life to you?",
  "Do you think people can truly change?",
  "What is the difference between a house and a home?",
  "Why do you think we dream?",
  "Is it better to have loved and lost than never to have loved at all?",
  "What is the biggest problem facing the world today?",
  "Do you think technology is making us lonelier?",
  "What is the value of art in society?",
  "Should we prioritize exploring the ocean or space?",
  "What does it mean to be a good friend?",
  "Is it possible to live a life without regrets?",
  "What is the most important human right?",
  "Do you believe in luck?",
  "What legacy do you want to leave behind?",

  // --- Random & Fun (231-250) ---
  "What is the funniest joke you know?",
  "Do you believe in ghosts or the supernatural?",
  "What is your favorite board game?",
  "Are you a dog person or a cat person?",
  "What is the worst haircut you ever had?",
  "What is a song that always gets stuck in your head?",
  "Do you prefer the city or the countryside?",
  "What is your favorite holiday and why?",
  "Are you an early bird or a night owl?",
  "What is the most embarrassing thing that happened to you in public?",
  "Do you collect anything?",
  "What is your favorite color and what does it say about you?",
  "Do you prefer calling or texting?",
  "What is the best gift you have ever received?",
  "Do you like surprises?",
  "What is a movie you can watch over and over again?",
  "Do you prefer summer or winter?",
  "What is your favorite ice cream flavor?",
  "Do you sing in the shower?",
  "What is the last photo you took on your phone?"
];
